import type { Metadata } from "next";
import { SWRConfig } from "swr";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SWRConfig
          value={{
            fetcher: (url) => fetch(url).then((res) => res.json()),
            revalidateOnFocus: false,
            dedupingInterval: 1000,
            errorRetryCount: 3,
            shouldRetryOnError: () => false,
            onError(err) {
              console.error("SWR global error", err);
            },
          }}
        >
          {children}
        </SWRConfig>
      </body>
    </html>
  );
}
